export const PAGE_ROUTES = {
  ROOT: '/',
  CREATE_PROPOSAL: 'create-proposal',
  ADD_BASIC_INFO: 'add-basic-info',
  VOTING_METHOD: 'voting-method',
  ENFORCE: 'setup-enforcer',
  DURATION: 'setup-duration',
  PARTICIPANTS: 'setup-participants',
  REVIEW_PROPOSAL: 'review-proposal',
  CONNECT_WALLET: 'connect-wallet',
  LOGIN: 'login',
  PAGE_SCREEN: 'page-screen',
  POLLING_METHOD: 'polling',
  PROPOSAL_OR_BLUEPRINT: 'proposal-or-blueprint',
  PROPOSAL_DETAIL: 'proposal-detail',
  MULTI_PROPOSAL: 'multi-proposal',
  INITIATIVE_DETAIL: 'initiative-detail',
  REVIEW_MODE_PROPOSAL: 'review-mode-proposal',
  INITIATIVE: {
    ROOT: 'initiative',
    SETUP_CHECKPOINT: 'setup-checkpoints',
    REVIEW_CHECKPOINT: 'review-checkpoint',
    ADD_INITIATIVE: 'add-initiative',
    REVIEW_CHECKPOINTS_TREE: 'review-checkpoints-tree',
    SET_UP_INITIATIVE: 'set-up-initiative',
    CHECKPOINT: 'checkpoint',
    ENFORCER: 'enforcer',
  },
  EDIT_BLUEPRINT: {
    ROOT: 'edit-blueprint',
    SETUP_CHECKPOINT: 'setup-checkpoints',
    PARTICIPANT_DETAIL: 'participant-detail',
    REVIEW_CHECKPOINT_TREE: 'review-checkpoint-tree',
  },
  WORKFLOW: {
    ROOT: 'blueprint',
    SET_NAME: 'set-name',
    ADD_PRIMARY_CP: 'add-primary-checkpoints',
    SETUP_CHECKPOINT: 'setup-checkpoints',
    SELECT_TEMPLATE: 'select-template',
    REVIEW_CP_TREE: 'review-checkpoint-tree',
    PARTICIPANT_DETAIL: 'participant-detail',
    EDIT: 'edit',
    WF_TEMPLATES: 'templates',
  },
  BASIC_INFO_FOR_INITIATIVES: 'basic-info-for-initiatives',
  ADD_APPROVALS: 'add-approvals',
  RESULT_VOTE: 'result-vote',
  REVIEW_INITIATIVES: 'review-initiatives',
};
export default PAGE_ROUTES;
