export const dataInitiativeCards = [
  {
    id: 1,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    subTitle: 'Hiring new graphic designer',
    title: 'Joey’s application',
    contentDate: 'Last modified on Dec 2nd, 2022',
    tagType: 'Draft',
  },
  {
    id: 2,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    subTitle: 'Hiring new graphic designer',
    title: 'Vincent’s application',
    date: 'Jan 10th, 2023',
    tagType: 'Pending',
  },
  {
    id: 3,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    subTitle: 'Investment',
    title: 'Axie Infinity Q2-2023 New Feature Release',
    date: 'Jan 10th, 2023',
    tagType: 'Active',
  },
  {
    id: 4,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    subTitle: 'Investment',
    title: 'Axie Infinity Q2-2023 New Feature Release',
    date: 'Jan 10th, 2023',
    tagType: 'Active',
  },
  {
    id: 5,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    subTitle: 'Hiring new graphic designer',
    title: 'Axie Infinity Q2-2023 New Feature Release',
    date: 'Jan 10th, 2023',
    tagType: 'Active',
  },
  {
    id: 6,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    subTitle: 'Hiring new graphic designer',
    title: 'Joey’s application',
    contentDate: 'Last modified on Dec 2nd, 2022',
    tagType: 'Draft',
  },
  {
    id: 7,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    subTitle: 'Hiring new graphic designer',
    title: 'Vincent’s application',
    date: 'Jan 10th, 2023',
    tagType: 'Pending',
  },
];

export const dataProposalCards = [
  {
    id: 1,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    title: 'Do you like Project Kepler?',
    decs: 'Project Kepler provides 10,368 Web 2&3 creators with a hyper-realistic metaverse platform where they can...',
    contentDate: '2 days left to active',
    tagType: 'Pending',
  },
  {
    id: 2,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'limon.eth',
    title: 'Upvote Space Mavericks to New Deal',
    decs: 'Upvote to see how many fellow Hectaholics are also interested in Space Mavericks.Space Mavericks i...',
    contentDate: 'Last modified on Dec 2nd, 2022',
    tagType: 'Draft',
  },
  {
    id: 3,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'franklindao.eth',
    title: 'Leo’s application',
    decs: 'TON is a network designed for speed and throughput. Fees are significantly lower than on other blockchains, ...',
    contentDate: '2 days left to active',
    tagType: 'Active',
  },
  {
    id: 4,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'franklindao.eth',
    title: 'Air’s deal',
    decs: "We announce the Manchester City's fan meeting information so we need your vote to decice when it be held.",
    contentDate: '2 days left to active',
    tagType: 'Pending',
  },
  {
    id: 5,
    urlAvatar: '/assets/images/temp/avatar-1.png',
    name: 'franklindao.eth',
    title: 'Leo’s application',
    decs: "We announce the Manchester City's fan meeting information so we need your vote to decice when it be held.",
    contentDate: '2 days left to active',
    tagType: 'Active',
  },
];

export const dataBluePrintCards = [
  {
    id: 1,
    tagType: 'Draft',
    contentDate: 'Last modified on Dec 2nd, 2022',
    amount: null,
    title: 'Investment process',
    dataAvatar: [
      '/assets/images/temp/avatar-2.png',
      '/assets/images/temp/avatar-4.png',
      '/assets/images/temp/avatar-3.png',
    ],
  },
  {
    id: 2,
    tagType: 'Draft',
    contentDate: 'Last modified on Dec 2nd, 2022',
    amount: 12,
    title: 'Hiring new graphic designer',
    dataAvatar: [
      '/assets/images/temp/avatar-2.png',
      '/assets/images/temp/avatar-4.png',
      '/assets/images/temp/avatar-3.png',
    ],
  },
  {
    id: 3,
    tagType: 'Draft',
    contentDate: 'Last modified on Dec 2nd, 2022',
    amount: 34,
    title: 'Restructure org',
    dataAvatar: [
      '/assets/images/temp/avatar-2.png',
      '/assets/images/temp/avatar-4.png',
      '/assets/images/temp/avatar-3.png',
    ],
  },
  {
    id: 4,
    tagType: 'Active',
    date: 'Dec 5th, 2022',
    amount: 23,
    title: 'Hiring new BD',
    dataAvatar: [
      '/assets/images/temp/avatar-2.png',
      '/assets/images/temp/avatar-4.png',
      '/assets/images/temp/avatar-3.png',
    ],
  },
  {
    id: 5,
    tagType: 'Active',
    date: 'Dec 5th, 2022',
    amount: 23,
    title: 'Hiring new BD',
    dataAvatar: [
      '/assets/images/temp/avatar-2.png',
      '/assets/images/temp/avatar-4.png',
      '/assets/images/temp/avatar-3.png',
    ],
  },
  {
    id: 6,
    tagType: 'Draft',
    contentDate: 'Last modified on Dec 2nd, 2022',
    amount: null,
    title: 'Investment process',
    dataAvatar: [
      '/assets/images/temp/avatar-2.png',
      '/assets/images/temp/avatar-4.png',
      '/assets/images/temp/avatar-3.png',
    ],
  },
];
