export const dataCardBlueprint = [
  {
    id: 1,
    urlImg: '/assets/images/temp/blueprint-1.png',
    urlAvatar: '/assets/images/temp/avatar-vote-1.png',
    title: 'Investment deals evaluation process for Investment DAO ',
    desc: 'Mjaki',
    active: true,
    popular: 0,
    recent: 0,
    tag: 'most-popular',
  },
  {
    id: 2,
    urlImg: '/assets/images/temp/blueprint-2.png',
    urlAvatar: '/assets/images/temp/avatar-vote-2.png',
    title: 'DAO contributors recruitment process',
    desc: 'Everest',
    active: true,
    popular: 0,
    recent: 0,
    tag: 'most-popular',
  },
  {
    id: 3,
    urlImg: '/assets/images/temp/blueprint-3.png',
    urlAvatar: '/assets/images/temp/avatar-vote-3.png',
    title: 'Product features decentralized selection process for DeFi or GameFi DAO',
    desc: 'Coming soon',
    active: false,
    popular: 1,
    recent: 1,
    tag: 'most-recent',
  },
  {
    id: 4,
    urlImg: '/assets/images/temp/blueprint-4.png',
    urlAvatar: '/assets/images/temp/avatar-vote-4.png',
    title: 'Beauty pageant judgement process with fans voting',
    desc: 'Coming soon',
    active: false,
    popular: 0,
    recent: 0,
    tag: 'most-popular',
  },
  {
    id: 5,
    urlImg: '/assets/images/temp/blueprint-5.png',
    urlAvatar: '/assets/images/temp/avatar-vote-5.png',
    title: 'Procurement competitive bidding process',
    desc: 'Coming soon',
    active: false,
    popular: 1,
    recent: 1,
    tag: 'most-recent',
  },
  {
    id: 6,
    urlImg: '/assets/images/temp/blueprint-6.png',
    urlAvatar: '/assets/images/temp/avatar-vote-6.png',
    title: 'Startup selection process for Accelerator or Incubator',
    desc: 'Coming soon',
    active: false,
    popular: 0,
    recent: 0,
    tag: 'most-popular',
  },
  {
    id: 7,
    urlImg: '/assets/images/temp/blueprint-7.png',
    urlAvatar: '/assets/images/temp/avatar-vote-1.png',
    title: 'Candidates selection process for Award, honour or prize',
    desc: 'Coming soon',
    active: false,
    popular: 0,
    recent: 1,
    tag: 'most-recent',
  },
  {
    id: 8,
    urlImg: '/assets/images/temp/blueprint-8.png',
    urlAvatar: '/assets/images/temp/avatar-vote-2.png',
    title: 'Startup competition judgement process',
    desc: 'Coming soon',
    active: false,
    popular: 1,
    recent: 0,
    tag: 'most-popular',
  },
  {
    id: 9,
    urlImg: '/assets/images/temp/blueprint-9.png',
    urlAvatar: '/assets/images/temp/avatar-vote-2.png',
    title: 'Business expense approval process',
    desc: 'Coming soon',
    active: false,
    popular: 0,
    recent: 1,
    tag: 'most-popular',
  },
  {
    id: 10,
    urlImg: '/assets/images/temp/blueprint-10.png',
    urlAvatar: '/assets/images/temp/avatar-vote-3.png',
    title: 'Charity activities planning process',
    desc: 'Coming soon',
    active: false,
    popular: 0,
    recent: 1,
    tag: 'most-popular',
  },
];

export const filterBlueprint = [
  {
    id: 'popular',
    label: 'Most popular',
  },
  {
    id: 'recent',
    label: 'Most recent',
  },
];
